Prendre les transports en commun pour le boulot
betagouv/ecolab-data pull request #708
Opened 2020-10-26 17:40 UTC by laem

- [ ] faire tourner le calcul

2020-11-10 14:47 UTC, Benjamin-Boisserie-ABC requested changes
C'est ok pour moi pour le codage (c'est plus clair même) mais pourquoi ne reprends tu pas le message descriptif que j'ai écrit ?

2020-11-12 12:09 UTC, mquandalle commented
Pour info j'ai mis à jour le Studio : il n'est plus nécessaire de définir des règles vides type `transport . bus:` 🙂 (le problème était l'affichage du fil d'Ariane dans la vue, cf. https://github.com/betagouv/mon-entreprise/commit/c6bd92d5f91f80a3ee2ccfbc0db8895fa11febbe)

2020-11-12 14:58 UTC, laem commented
>  pourquoi ne reprends tu pas le message descriptif que j'ai écrit ?

En effet j'aurais pu en dire un peu plus que seulement le texte du commit : c'était notamment pour raccourcir (comme j'ai pu) le texte pour qu'il soit le plus synthétique possible sur la fiche qui doit s'afficher sur mobile. Par exemple, "contribue à déteriorer" -> "détériore", ou éviter les répétitions comme "et à encombrer les voies urbaines" puis "tout en décongestionnant les voies urbaines".

Mais aussi : 
- mettre l'exemple de l'IdF en bas, formatté visuellement comme un exemple avec le chevron >
- mettre l'enseignement principal en haut
- mettre les sources des 2 chiffres avancées directement en lien dans le texte
- ne pas utiliser l'acronyme GES qui ne sera compris que par les experts

2020-11-16 15:30 UTC, Benjamin-Boisserie-ABC approved these changes

2020-11-16 15:34 UTC, merged